name: Detekt Publish Release

on:
  push:
    tags:
      - 'detekt_*'

jobs:
  publish-release:
    uses: ./.github/workflows/publish-release-workflow.yaml
    with:
      project: detekt
    secrets: inherit
