name: Yamllint Publish Release

on:
  push:
    tags:
      - 'yamllint_*'

jobs:
  publish-release:
    uses: ./.github/workflows/publish-release-workflow.yaml
    with:
      project: yamllint
    secrets: inherit
