name: Publish Snapshot

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [ shellcheck, yamllint, core ]

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish Snapshot
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          PACKAGE: ${{ matrix.package }}
        run: ./gradlew :$PACKAGE:publish -PartifactIdProperty=$PACKAGE
