name: Shellcheck Publish Release

on:
  push:
    tags:
      - 'shellcheck_*'

jobs:
  publish-release:
    uses: ./.github/workflows/publish-release-workflow.yml
    with:
      project: shellcheck
    secrets: inherit
